### NORMALIZATION PROBLEM


### Problem: Data Normalization

- In data analytics, normalization is an essential preprocessing method, particularly for statistical and machine learning applications. Scaling and centering the data are involved.


- Subtracting each data point's mean from the total is referred to as centering. By taking this step, the data's mean of zero is guaranteed.


- The process of dividing the centered data by the standard deviation is called scaling. By doing this, the data are standardized to have a standard deviation of 1. 


- By ensuring that the data is on a consistent scale, this method helps minimize bias towards features with bigger sizes and enhances the performance of numerous machine learning methods.


##### Input format: The program receives no specific input, but it should use the 'np.random.randon((5, 5))' function to produce a random 5x5 array of floating-point numbers between 0 and 1.


##### Output format: The 5x5 normalized NumPy array is the output, which is saved to a file called 'X_normalized.npy.'



In [1]:
#Start: Getting the library using np to shorten numpy 
import numpy as np 

#Creating a random 5x5 ndarray and store it in variable X 
X = np.random.random((5, 5))

#Centering and scaling (Normalized X)
X_mean = X.mean()
X_std = X.std()
X_normalized = (X - X_mean) / X_std

#Saving the Normalized ndarray as a file 
np.save('X_normalized.npy', X_normalized)

#Checking there is a difference between X and Normalized X
print("The Original X: \n", X, "\n")
print("The Normalized X: \n", X_normalized) 

The Original X: 
 [[0.49359275 0.55637242 0.88260865 0.18572574 0.67821987]
 [0.38585091 0.257146   0.73537277 0.6321534  0.42170025]
 [0.72303258 0.60853675 0.96732221 0.5850818  0.53509258]
 [0.48261404 0.49579075 0.34351044 0.35683352 0.73636125]
 [0.11335986 0.85504277 0.51203765 0.36522279 0.78806262]] 

The Normalized X: 
 [[-0.25412813  0.03983152  1.5674007  -1.69568517  0.61037024]
 [-0.75861873 -1.36126685  0.8779831   0.39466856 -0.59075768]
 [ 0.82020137  0.2840859   1.96406362  0.17426039 -0.05980922]
 [-0.30553485 -0.24383621 -0.9568738  -0.89448978  0.88261157]
 [-2.03453133  1.43832613 -0.16776166 -0.85520785  1.12469817]]


### DIVISIBLE BY 3 PROBLEM

### Problem: Finding Elements Divisible by 3 in a Squared Matrix

- The task involves generating a 10x10 NumPy array, with each element representing the square of the initial 100 positive integers, ranging from 1^2 to 100^2. The next step is to build this array and then find and remove every element that divides by three. It is necessary to save the outcome to a file.

##### Input format: The program receives no particular input. Still, the software ought to: Create a NumPy array with all of the integers from 1 to 100 squared.

##### Output format: The program will produce: The array containing the squares of integers from 1 to 100, An array of items in NumPy that divide by three, These components are going to be stored in a file called "div_by_3.npy." 

- The array will be stored to "div_by_3.npy" and contain numbers like 9, 36, 81, 144, 324, etc. after the elements divisible by 3 have been found.



In [2]:
#Start: Getting the library using np to shorten numpy
import numpy as np 

#Creating a 10x10 ndarray of squares of the first 100 positive intergers 
A = np.arange(1, 101).reshape(10, 10) ** 2 

#Determining elements divisible by 3 
div_by_3 = A[A % 3 == 0].reshape(3, 11)

#Saving the elements to a file 
np.save('div_by_3.npy', div_by_3)


#Printing the squares of the first 100 positive integers 
print("A = \n", A, "\n")

#Printing the all Elements divisble by 3
print("All the elements that are divisible by 3 = \n", div_by_3) 

A = 
 [[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]] 

All the elements that are divisible by 3 = 
 [[   9   36   81  144  225  324  441  576  729  900 1089]
 [1296 1521 1764 2025 2304 2601 2916 3249 3600 3969 4356]
 [4761 5184 5625 6084 6561 7056 7569 8100 8649 9216 9801]]
